### ISSUE TITLE
Introduce GPLv3 license

### ISSUE THREAD

**Issue by lfse-slafleur** [Project-OMOTES/computation-engine#57]

**Comment by lfse-slafleur** [comment]
@martijnclarijs  @samvanderzwan Could you, as representatives of both Deltares & TNO who are currently the sole owners and contributors of the OMOTES code bases, confirm that we can switch to GPLv3? A reply to this message should suffice.

**Comment by martijnclarijs** [comment]
Yes, confirmed


Dr. ir. M.C. (Martijn) Clarijs
Senior Business Consultant
Sustainable Energy
Heat Transfer & Fluid Dynamics
T +31 (0)88 866 25 06
M +31 (0)63 179 28 34
E ***@***.******@***.***>



***@***.***<http://www.tno.nl/>
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by samvanderzwan** [comment]
Confirmed

**Comment by samvanderzwan** [comment]
Confirmed
